export const generateSampleTimetable = (teacher1Id, teacher2Id) => {
  return [
    // ----------------- MONDAY (2026-08-17) -----------------
    {
      date: '2026-08-17',
      day: 'Monday',
      startTime: '09:00',
      endTime: '10:00',
      subject: 'Software Engineering',
      subjectCode: 'CS801',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 301'
    },
    {
      date: '2026-08-17',
      day: 'Monday',
      startTime: '10:15',
      endTime: '11:15',
      subject: 'Distributed Systems',
      subjectCode: 'CS802',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 302'
    },
    {
      date: '2026-08-17',
      day: 'Monday',
      startTime: '11:30',
      endTime: '12:30',
      subject: 'Cloud Computing',
      subjectCode: 'CS803',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 401'
    },
    {
      date: '2026-08-17',
      day: 'Monday',
      startTime: '14:00',
      endTime: '16:00',
      subject: 'Cloud & AI Practical Lab (Batch 1)',
      subjectCode: 'CS803-L1',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: 1,
      room: 'Comp Lab 1'
    },

    // ----------------- TUESDAY (2026-08-18) -----------------
    {
      date: '2026-08-18',
      day: 'Tuesday',
      startTime: '09:00',
      endTime: '10:00',
      subject: 'Artificial Intelligence',
      subjectCode: 'CS804',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 401'
    },
    {
      date: '2026-08-18',
      day: 'Tuesday',
      startTime: '10:15',
      endTime: '11:15',
      subject: 'Software Engineering',
      subjectCode: 'CS801',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 301'
    },
    {
      date: '2026-08-18',
      day: 'Tuesday',
      startTime: '11:30',
      endTime: '12:30',
      subject: 'Distributed Systems',
      subjectCode: 'CS802',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 302'
    },
    {
      date: '2026-08-18',
      day: 'Tuesday',
      startTime: '14:00',
      endTime: '16:00',
      subject: 'Software Engineering Lab (Batch 2)',
      subjectCode: 'CS801-L2',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: 2,
      room: 'Comp Lab 2'
    },

    // ----------------- WEDNESDAY (2026-08-19) -----------------
    {
      date: '2026-08-19',
      day: 'Wednesday',
      startTime: '09:00',
      endTime: '10:00',
      subject: 'Software Engineering',
      subjectCode: 'CS801',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 301'
    },
    {
      date: '2026-08-19',
      day: 'Wednesday',
      startTime: '10:15',
      endTime: '11:15',
      subject: 'Cloud Computing',
      subjectCode: 'CS803',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 401'
    },
    {
      date: '2026-08-19',
      day: 'Wednesday',
      startTime: '11:30',
      endTime: '12:30',
      subject: 'Distributed Systems',
      subjectCode: 'CS802',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 302'
    },
    {
      date: '2026-08-19',
      day: 'Wednesday',
      startTime: '14:00',
      endTime: '16:00',
      subject: 'Distributed Systems Lab (Batch 1)',
      subjectCode: 'CS802-L1',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: 1,
      room: 'Comp Lab 3'
    },

    // ----------------- THURSDAY (2026-08-20) -----------------
    {
      date: '2026-08-20',
      day: 'Thursday',
      startTime: '09:00',
      endTime: '10:00',
      subject: 'Artificial Intelligence',
      subjectCode: 'CS804',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 401'
    },
    {
      date: '2026-08-20',
      day: 'Thursday',
      startTime: '10:15',
      endTime: '11:15',
      subject: 'Distributed Systems',
      subjectCode: 'CS802',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 302'
    },
    {
      date: '2026-08-20',
      day: 'Thursday',
      startTime: '11:30',
      endTime: '12:30',
      subject: 'Cloud Computing',
      subjectCode: 'CS803',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 401'
    },
    {
      date: '2026-08-20',
      day: 'Thursday',
      startTime: '14:00',
      endTime: '16:00',
      subject: 'Cloud & AI Practical Lab (Batch 3)',
      subjectCode: 'CS803-L3',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: 3,
      room: 'Comp Lab 1'
    },

    // ----------------- FRIDAY (2026-08-21) -----------------
    {
      date: '2026-08-21',
      day: 'Friday',
      startTime: '09:00',
      endTime: '10:00',
      subject: 'Software Engineering',
      subjectCode: 'CS801',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 301'
    },
    {
      date: '2026-08-21',
      day: 'Friday',
      startTime: '10:15',
      endTime: '11:15',
      subject: 'Distributed Systems',
      subjectCode: 'CS802',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 302'
    },
    {
      date: '2026-08-21',
      day: 'Friday',
      startTime: '11:30',
      endTime: '12:30',
      subject: 'Artificial Intelligence',
      subjectCode: 'CS804',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 401'
    },

    // ----------------- SATURDAY (2026-08-22) -----------------
    {
      date: '2026-08-22',
      day: 'Saturday',
      startTime: '09:30',
      endTime: '11:00',
      subject: 'Advanced Cloud Architectures (Special Seminar)',
      subjectCode: 'CS803-SEM',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Auditorium 2'
    },

    // ----------------- MONDAY NEXT (2026-08-24) -----------------
    {
      date: '2026-08-24',
      day: 'Monday',
      startTime: '09:00',
      endTime: '10:00',
      subject: 'Software Engineering',
      subjectCode: 'CS801',
      teacherId: teacher1Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 301'
    },
    {
      date: '2026-08-24',
      day: 'Monday',
      startTime: '10:15',
      endTime: '11:15',
      subject: 'Cloud Computing',
      subjectCode: 'CS803',
      teacherId: teacher2Id,
      year: 'BE',
      branch: 'COMPS',
      classNumber: 1,
      batch: null,
      room: 'Room 401'
    }
  ];
};
